# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.13

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /home/pegasus/Downloads/clion-2018.3.3/bin/cmake/linux/bin/cmake

# The command to remove a file.
RM = /home/pegasus/Downloads/clion-2018.3.3/bin/cmake/linux/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/pegasus/libcarbon

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/pegasus/libcarbon

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/home/pegasus/Downloads/clion-2018.3.3/bin/cmake/linux/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/home/pegasus/Downloads/clion-2018.3.3/bin/cmake/linux/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/home/pegasus/Downloads/clion-2018.3.3/bin/cmake/linux/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/home/pegasus/Downloads/clion-2018.3.3/bin/cmake/linux/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components

.PHONY : list_install_components/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/home/pegasus/Downloads/clion-2018.3.3/bin/cmake/linux/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/home/pegasus/Downloads/clion-2018.3.3/bin/cmake/linux/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/home/pegasus/Downloads/clion-2018.3.3/bin/cmake/linux/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/home/pegasus/Downloads/clion-2018.3.3/bin/cmake/linux/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/pegasus/libcarbon/CMakeFiles /home/pegasus/libcarbon/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/pegasus/libcarbon/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named carbon

# Build rule for target.
carbon: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 carbon
.PHONY : carbon

# fast build rule for target.
carbon/fast:
	$(MAKE) -f CMakeFiles/carbon.dir/build.make CMakeFiles/carbon.dir/build
.PHONY : carbon/fast

#=============================================================================
# Target rules for targets named carbon-tool

# Build rule for target.
carbon-tool: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 carbon-tool
.PHONY : carbon-tool

# fast build rule for target.
carbon-tool/fast:
	$(MAKE) -f tools/carbon/CMakeFiles/carbon-tool.dir/build.make tools/carbon/CMakeFiles/carbon-tool.dir/build
.PHONY : carbon-tool/fast

#=============================================================================
# Target rules for targets named examples-error

# Build rule for target.
examples-error: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 examples-error
.PHONY : examples-error

# fast build rule for target.
examples-error/fast:
	$(MAKE) -f examples/CMakeFiles/examples-error.dir/build.make examples/CMakeFiles/examples-error.dir/build
.PHONY : examples-error/fast

src/carbon/alloc/carbon-alloc-tracer.o: src/carbon/alloc/carbon-alloc-tracer.c.o

.PHONY : src/carbon/alloc/carbon-alloc-tracer.o

# target to build an object file
src/carbon/alloc/carbon-alloc-tracer.c.o:
	$(MAKE) -f CMakeFiles/carbon.dir/build.make CMakeFiles/carbon.dir/src/carbon/alloc/carbon-alloc-tracer.c.o
.PHONY : src/carbon/alloc/carbon-alloc-tracer.c.o

src/carbon/alloc/carbon-alloc-tracer.i: src/carbon/alloc/carbon-alloc-tracer.c.i

.PHONY : src/carbon/alloc/carbon-alloc-tracer.i

# target to preprocess a source file
src/carbon/alloc/carbon-alloc-tracer.c.i:
	$(MAKE) -f CMakeFiles/carbon.dir/build.make CMakeFiles/carbon.dir/src/carbon/alloc/carbon-alloc-tracer.c.i
.PHONY : src/carbon/alloc/carbon-alloc-tracer.c.i

src/carbon/alloc/carbon-alloc-tracer.s: src/carbon/alloc/carbon-alloc-tracer.c.s

.PHONY : src/carbon/alloc/carbon-alloc-tracer.s

# target to generate assembly for a file
src/carbon/alloc/carbon-alloc-tracer.c.s:
	$(MAKE) -f CMakeFiles/carbon.dir/build.make CMakeFiles/carbon.dir/src/carbon/alloc/carbon-alloc-tracer.c.s
.PHONY : src/carbon/alloc/carbon-alloc-tracer.c.s

src/carbon/carbon-alloc.o: src/carbon/carbon-alloc.c.o

.PHONY : src/carbon/carbon-alloc.o

# target to build an object file
src/carbon/carbon-alloc.c.o:
	$(MAKE) -f CMakeFiles/carbon.dir/build.make CMakeFiles/carbon.dir/src/carbon/carbon-alloc.c.o
.PHONY : src/carbon/carbon-alloc.c.o

src/carbon/carbon-alloc.i: src/carbon/carbon-alloc.c.i

.PHONY : src/carbon/carbon-alloc.i

# target to preprocess a source file
src/carbon/carbon-alloc.c.i:
	$(MAKE) -f CMakeFiles/carbon.dir/build.make CMakeFiles/carbon.dir/src/carbon/carbon-alloc.c.i
.PHONY : src/carbon/carbon-alloc.c.i

src/carbon/carbon-alloc.s: src/carbon/carbon-alloc.c.s

.PHONY : src/carbon/carbon-alloc.s

# target to generate assembly for a file
src/carbon/carbon-alloc.c.s:
	$(MAKE) -f CMakeFiles/carbon.dir/build.make CMakeFiles/carbon.dir/src/carbon/carbon-alloc.c.s
.PHONY : src/carbon/carbon-alloc.c.s

src/carbon/carbon-archive.o: src/carbon/carbon-archive.c.o

.PHONY : src/carbon/carbon-archive.o

# target to build an object file
src/carbon/carbon-archive.c.o:
	$(MAKE) -f CMakeFiles/carbon.dir/build.make CMakeFiles/carbon.dir/src/carbon/carbon-archive.c.o
.PHONY : src/carbon/carbon-archive.c.o

src/carbon/carbon-archive.i: src/carbon/carbon-archive.c.i

.PHONY : src/carbon/carbon-archive.i

# target to preprocess a source file
src/carbon/carbon-archive.c.i:
	$(MAKE) -f CMakeFiles/carbon.dir/build.make CMakeFiles/carbon.dir/src/carbon/carbon-archive.c.i
.PHONY : src/carbon/carbon-archive.c.i

src/carbon/carbon-archive.s: src/carbon/carbon-archive.c.s

.PHONY : src/carbon/carbon-archive.s

# target to generate assembly for a file
src/carbon/carbon-archive.c.s:
	$(MAKE) -f CMakeFiles/carbon.dir/build.make CMakeFiles/carbon.dir/src/carbon/carbon-archive.c.s
.PHONY : src/carbon/carbon-archive.c.s

src/carbon/carbon-bitmap.o: src/carbon/carbon-bitmap.c.o

.PHONY : src/carbon/carbon-bitmap.o

# target to build an object file
src/carbon/carbon-bitmap.c.o:
	$(MAKE) -f CMakeFiles/carbon.dir/build.make CMakeFiles/carbon.dir/src/carbon/carbon-bitmap.c.o
.PHONY : src/carbon/carbon-bitmap.c.o

src/carbon/carbon-bitmap.i: src/carbon/carbon-bitmap.c.i

.PHONY : src/carbon/carbon-bitmap.i

# target to preprocess a source file
src/carbon/carbon-bitmap.c.i:
	$(MAKE) -f CMakeFiles/carbon.dir/build.make CMakeFiles/carbon.dir/src/carbon/carbon-bitmap.c.i
.PHONY : src/carbon/carbon-bitmap.c.i

src/carbon/carbon-bitmap.s: src/carbon/carbon-bitmap.c.s

.PHONY : src/carbon/carbon-bitmap.s

# target to generate assembly for a file
src/carbon/carbon-bitmap.c.s:
	$(MAKE) -f CMakeFiles/carbon.dir/build.make CMakeFiles/carbon.dir/src/carbon/carbon-bitmap.c.s
.PHONY : src/carbon/carbon-bitmap.c.s

src/carbon/carbon-bloom.o: src/carbon/carbon-bloom.c.o

.PHONY : src/carbon/carbon-bloom.o

# target to build an object file
src/carbon/carbon-bloom.c.o:
	$(MAKE) -f CMakeFiles/carbon.dir/build.make CMakeFiles/carbon.dir/src/carbon/carbon-bloom.c.o
.PHONY : src/carbon/carbon-bloom.c.o

src/carbon/carbon-bloom.i: src/carbon/carbon-bloom.c.i

.PHONY : src/carbon/carbon-bloom.i

# target to preprocess a source file
src/carbon/carbon-bloom.c.i:
	$(MAKE) -f CMakeFiles/carbon.dir/build.make CMakeFiles/carbon.dir/src/carbon/carbon-bloom.c.i
.PHONY : src/carbon/carbon-bloom.c.i

src/carbon/carbon-bloom.s: src/carbon/carbon-bloom.c.s

.PHONY : src/carbon/carbon-bloom.s

# target to generate assembly for a file
src/carbon/carbon-bloom.c.s:
	$(MAKE) -f CMakeFiles/carbon.dir/build.make CMakeFiles/carbon.dir/src/carbon/carbon-bloom.c.s
.PHONY : src/carbon/carbon-bloom.c.s

src/carbon/carbon-columndoc.o: src/carbon/carbon-columndoc.c.o

.PHONY : src/carbon/carbon-columndoc.o

# target to build an object file
src/carbon/carbon-columndoc.c.o:
	$(MAKE) -f CMakeFiles/carbon.dir/build.make CMakeFiles/carbon.dir/src/carbon/carbon-columndoc.c.o
.PHONY : src/carbon/carbon-columndoc.c.o

src/carbon/carbon-columndoc.i: src/carbon/carbon-columndoc.c.i

.PHONY : src/carbon/carbon-columndoc.i

# target to preprocess a source file
src/carbon/carbon-columndoc.c.i:
	$(MAKE) -f CMakeFiles/carbon.dir/build.make CMakeFiles/carbon.dir/src/carbon/carbon-columndoc.c.i
.PHONY : src/carbon/carbon-columndoc.c.i

src/carbon/carbon-columndoc.s: src/carbon/carbon-columndoc.c.s

.PHONY : src/carbon/carbon-columndoc.s

# target to generate assembly for a file
src/carbon/carbon-columndoc.c.s:
	$(MAKE) -f CMakeFiles/carbon.dir/build.make CMakeFiles/carbon.dir/src/carbon/carbon-columndoc.c.s
.PHONY : src/carbon/carbon-columndoc.c.s

src/carbon/carbon-convert.o: src/carbon/carbon-convert.c.o

.PHONY : src/carbon/carbon-convert.o

# target to build an object file
src/carbon/carbon-convert.c.o:
	$(MAKE) -f CMakeFiles/carbon.dir/build.make CMakeFiles/carbon.dir/src/carbon/carbon-convert.c.o
.PHONY : src/carbon/carbon-convert.c.o

src/carbon/carbon-convert.i: src/carbon/carbon-convert.c.i

.PHONY : src/carbon/carbon-convert.i

# target to preprocess a source file
src/carbon/carbon-convert.c.i:
	$(MAKE) -f CMakeFiles/carbon.dir/build.make CMakeFiles/carbon.dir/src/carbon/carbon-convert.c.i
.PHONY : src/carbon/carbon-convert.c.i

src/carbon/carbon-convert.s: src/carbon/carbon-convert.c.s

.PHONY : src/carbon/carbon-convert.s

# target to generate assembly for a file
src/carbon/carbon-convert.c.s:
	$(MAKE) -f CMakeFiles/carbon.dir/build.make CMakeFiles/carbon.dir/src/carbon/carbon-convert.c.s
.PHONY : src/carbon/carbon-convert.c.s

src/carbon/carbon-doc.o: src/carbon/carbon-doc.c.o

.PHONY : src/carbon/carbon-doc.o

# target to build an object file
src/carbon/carbon-doc.c.o:
	$(MAKE) -f CMakeFiles/carbon.dir/build.make CMakeFiles/carbon.dir/src/carbon/carbon-doc.c.o
.PHONY : src/carbon/carbon-doc.c.o

src/carbon/carbon-doc.i: src/carbon/carbon-doc.c.i

.PHONY : src/carbon/carbon-doc.i

# target to preprocess a source file
src/carbon/carbon-doc.c.i:
	$(MAKE) -f CMakeFiles/carbon.dir/build.make CMakeFiles/carbon.dir/src/carbon/carbon-doc.c.i
.PHONY : src/carbon/carbon-doc.c.i

src/carbon/carbon-doc.s: src/carbon/carbon-doc.c.s

.PHONY : src/carbon/carbon-doc.s

# target to generate assembly for a file
src/carbon/carbon-doc.c.s:
	$(MAKE) -f CMakeFiles/carbon.dir/build.make CMakeFiles/carbon.dir/src/carbon/carbon-doc.c.s
.PHONY : src/carbon/carbon-doc.c.s

src/carbon/carbon-error.o: src/carbon/carbon-error.c.o

.PHONY : src/carbon/carbon-error.o

# target to build an object file
src/carbon/carbon-error.c.o:
	$(MAKE) -f CMakeFiles/carbon.dir/build.make CMakeFiles/carbon.dir/src/carbon/carbon-error.c.o
.PHONY : src/carbon/carbon-error.c.o

src/carbon/carbon-error.i: src/carbon/carbon-error.c.i

.PHONY : src/carbon/carbon-error.i

# target to preprocess a source file
src/carbon/carbon-error.c.i:
	$(MAKE) -f CMakeFiles/carbon.dir/build.make CMakeFiles/carbon.dir/src/carbon/carbon-error.c.i
.PHONY : src/carbon/carbon-error.c.i

src/carbon/carbon-error.s: src/carbon/carbon-error.c.s

.PHONY : src/carbon/carbon-error.s

# target to generate assembly for a file
src/carbon/carbon-error.c.s:
	$(MAKE) -f CMakeFiles/carbon.dir/build.make CMakeFiles/carbon.dir/src/carbon/carbon-error.c.s
.PHONY : src/carbon/carbon-error.c.s

src/carbon/carbon-huffman.o: src/carbon/carbon-huffman.c.o

.PHONY : src/carbon/carbon-huffman.o

# target to build an object file
src/carbon/carbon-huffman.c.o:
	$(MAKE) -f CMakeFiles/carbon.dir/build.make CMakeFiles/carbon.dir/src/carbon/carbon-huffman.c.o
.PHONY : src/carbon/carbon-huffman.c.o

src/carbon/carbon-huffman.i: src/carbon/carbon-huffman.c.i

.PHONY : src/carbon/carbon-huffman.i

# target to preprocess a source file
src/carbon/carbon-huffman.c.i:
	$(MAKE) -f CMakeFiles/carbon.dir/build.make CMakeFiles/carbon.dir/src/carbon/carbon-huffman.c.i
.PHONY : src/carbon/carbon-huffman.c.i

src/carbon/carbon-huffman.s: src/carbon/carbon-huffman.c.s

.PHONY : src/carbon/carbon-huffman.s

# target to generate assembly for a file
src/carbon/carbon-huffman.c.s:
	$(MAKE) -f CMakeFiles/carbon.dir/build.make CMakeFiles/carbon.dir/src/carbon/carbon-huffman.c.s
.PHONY : src/carbon/carbon-huffman.c.s

src/carbon/carbon-json.o: src/carbon/carbon-json.c.o

.PHONY : src/carbon/carbon-json.o

# target to build an object file
src/carbon/carbon-json.c.o:
	$(MAKE) -f CMakeFiles/carbon.dir/build.make CMakeFiles/carbon.dir/src/carbon/carbon-json.c.o
.PHONY : src/carbon/carbon-json.c.o

src/carbon/carbon-json.i: src/carbon/carbon-json.c.i

.PHONY : src/carbon/carbon-json.i

# target to preprocess a source file
src/carbon/carbon-json.c.i:
	$(MAKE) -f CMakeFiles/carbon.dir/build.make CMakeFiles/carbon.dir/src/carbon/carbon-json.c.i
.PHONY : src/carbon/carbon-json.c.i

src/carbon/carbon-json.s: src/carbon/carbon-json.c.s

.PHONY : src/carbon/carbon-json.s

# target to generate assembly for a file
src/carbon/carbon-json.c.s:
	$(MAKE) -f CMakeFiles/carbon.dir/build.make CMakeFiles/carbon.dir/src/carbon/carbon-json.c.s
.PHONY : src/carbon/carbon-json.c.s

src/carbon/carbon-memblock.o: src/carbon/carbon-memblock.c.o

.PHONY : src/carbon/carbon-memblock.o

# target to build an object file
src/carbon/carbon-memblock.c.o:
	$(MAKE) -f CMakeFiles/carbon.dir/build.make CMakeFiles/carbon.dir/src/carbon/carbon-memblock.c.o
.PHONY : src/carbon/carbon-memblock.c.o

src/carbon/carbon-memblock.i: src/carbon/carbon-memblock.c.i

.PHONY : src/carbon/carbon-memblock.i

# target to preprocess a source file
src/carbon/carbon-memblock.c.i:
	$(MAKE) -f CMakeFiles/carbon.dir/build.make CMakeFiles/carbon.dir/src/carbon/carbon-memblock.c.i
.PHONY : src/carbon/carbon-memblock.c.i

src/carbon/carbon-memblock.s: src/carbon/carbon-memblock.c.s

.PHONY : src/carbon/carbon-memblock.s

# target to generate assembly for a file
src/carbon/carbon-memblock.c.s:
	$(MAKE) -f CMakeFiles/carbon.dir/build.make CMakeFiles/carbon.dir/src/carbon/carbon-memblock.c.s
.PHONY : src/carbon/carbon-memblock.c.s

src/carbon/carbon-memfile.o: src/carbon/carbon-memfile.c.o

.PHONY : src/carbon/carbon-memfile.o

# target to build an object file
src/carbon/carbon-memfile.c.o:
	$(MAKE) -f CMakeFiles/carbon.dir/build.make CMakeFiles/carbon.dir/src/carbon/carbon-memfile.c.o
.PHONY : src/carbon/carbon-memfile.c.o

src/carbon/carbon-memfile.i: src/carbon/carbon-memfile.c.i

.PHONY : src/carbon/carbon-memfile.i

# target to preprocess a source file
src/carbon/carbon-memfile.c.i:
	$(MAKE) -f CMakeFiles/carbon.dir/build.make CMakeFiles/carbon.dir/src/carbon/carbon-memfile.c.i
.PHONY : src/carbon/carbon-memfile.c.i

src/carbon/carbon-memfile.s: src/carbon/carbon-memfile.c.s

.PHONY : src/carbon/carbon-memfile.s

# target to generate assembly for a file
src/carbon/carbon-memfile.c.s:
	$(MAKE) -f CMakeFiles/carbon.dir/build.make CMakeFiles/carbon.dir/src/carbon/carbon-memfile.c.s
.PHONY : src/carbon/carbon-memfile.c.s

src/carbon/carbon-slicelist.o: src/carbon/carbon-slicelist.c.o

.PHONY : src/carbon/carbon-slicelist.o

# target to build an object file
src/carbon/carbon-slicelist.c.o:
	$(MAKE) -f CMakeFiles/carbon.dir/build.make CMakeFiles/carbon.dir/src/carbon/carbon-slicelist.c.o
.PHONY : src/carbon/carbon-slicelist.c.o

src/carbon/carbon-slicelist.i: src/carbon/carbon-slicelist.c.i

.PHONY : src/carbon/carbon-slicelist.i

# target to preprocess a source file
src/carbon/carbon-slicelist.c.i:
	$(MAKE) -f CMakeFiles/carbon.dir/build.make CMakeFiles/carbon.dir/src/carbon/carbon-slicelist.c.i
.PHONY : src/carbon/carbon-slicelist.c.i

src/carbon/carbon-slicelist.s: src/carbon/carbon-slicelist.c.s

.PHONY : src/carbon/carbon-slicelist.s

# target to generate assembly for a file
src/carbon/carbon-slicelist.c.s:
	$(MAKE) -f CMakeFiles/carbon.dir/build.make CMakeFiles/carbon.dir/src/carbon/carbon-slicelist.c.s
.PHONY : src/carbon/carbon-slicelist.c.s

src/carbon/carbon-spinlock.o: src/carbon/carbon-spinlock.c.o

.PHONY : src/carbon/carbon-spinlock.o

# target to build an object file
src/carbon/carbon-spinlock.c.o:
	$(MAKE) -f CMakeFiles/carbon.dir/build.make CMakeFiles/carbon.dir/src/carbon/carbon-spinlock.c.o
.PHONY : src/carbon/carbon-spinlock.c.o

src/carbon/carbon-spinlock.i: src/carbon/carbon-spinlock.c.i

.PHONY : src/carbon/carbon-spinlock.i

# target to preprocess a source file
src/carbon/carbon-spinlock.c.i:
	$(MAKE) -f CMakeFiles/carbon.dir/build.make CMakeFiles/carbon.dir/src/carbon/carbon-spinlock.c.i
.PHONY : src/carbon/carbon-spinlock.c.i

src/carbon/carbon-spinlock.s: src/carbon/carbon-spinlock.c.s

.PHONY : src/carbon/carbon-spinlock.s

# target to generate assembly for a file
src/carbon/carbon-spinlock.c.s:
	$(MAKE) -f CMakeFiles/carbon.dir/build.make CMakeFiles/carbon.dir/src/carbon/carbon-spinlock.c.s
.PHONY : src/carbon/carbon-spinlock.c.s

src/carbon/carbon-time.o: src/carbon/carbon-time.c.o

.PHONY : src/carbon/carbon-time.o

# target to build an object file
src/carbon/carbon-time.c.o:
	$(MAKE) -f CMakeFiles/carbon.dir/build.make CMakeFiles/carbon.dir/src/carbon/carbon-time.c.o
.PHONY : src/carbon/carbon-time.c.o

src/carbon/carbon-time.i: src/carbon/carbon-time.c.i

.PHONY : src/carbon/carbon-time.i

# target to preprocess a source file
src/carbon/carbon-time.c.i:
	$(MAKE) -f CMakeFiles/carbon.dir/build.make CMakeFiles/carbon.dir/src/carbon/carbon-time.c.i
.PHONY : src/carbon/carbon-time.c.i

src/carbon/carbon-time.s: src/carbon/carbon-time.c.s

.PHONY : src/carbon/carbon-time.s

# target to generate assembly for a file
src/carbon/carbon-time.c.s:
	$(MAKE) -f CMakeFiles/carbon.dir/build.make CMakeFiles/carbon.dir/src/carbon/carbon-time.c.s
.PHONY : src/carbon/carbon-time.c.s

src/carbon/carbon-vector.o: src/carbon/carbon-vector.c.o

.PHONY : src/carbon/carbon-vector.o

# target to build an object file
src/carbon/carbon-vector.c.o:
	$(MAKE) -f CMakeFiles/carbon.dir/build.make CMakeFiles/carbon.dir/src/carbon/carbon-vector.c.o
.PHONY : src/carbon/carbon-vector.c.o

src/carbon/carbon-vector.i: src/carbon/carbon-vector.c.i

.PHONY : src/carbon/carbon-vector.i

# target to preprocess a source file
src/carbon/carbon-vector.c.i:
	$(MAKE) -f CMakeFiles/carbon.dir/build.make CMakeFiles/carbon.dir/src/carbon/carbon-vector.c.i
.PHONY : src/carbon/carbon-vector.c.i

src/carbon/carbon-vector.s: src/carbon/carbon-vector.c.s

.PHONY : src/carbon/carbon-vector.s

# target to generate assembly for a file
src/carbon/carbon-vector.c.s:
	$(MAKE) -f CMakeFiles/carbon.dir/build.make CMakeFiles/carbon.dir/src/carbon/carbon-vector.c.s
.PHONY : src/carbon/carbon-vector.c.s

src/carbon/carbon.o: src/carbon/carbon.c.o

.PHONY : src/carbon/carbon.o

# target to build an object file
src/carbon/carbon.c.o:
	$(MAKE) -f CMakeFiles/carbon.dir/build.make CMakeFiles/carbon.dir/src/carbon/carbon.c.o
.PHONY : src/carbon/carbon.c.o

src/carbon/carbon.i: src/carbon/carbon.c.i

.PHONY : src/carbon/carbon.i

# target to preprocess a source file
src/carbon/carbon.c.i:
	$(MAKE) -f CMakeFiles/carbon.dir/build.make CMakeFiles/carbon.dir/src/carbon/carbon.c.i
.PHONY : src/carbon/carbon.c.i

src/carbon/carbon.s: src/carbon/carbon.c.s

.PHONY : src/carbon/carbon.s

# target to generate assembly for a file
src/carbon/carbon.c.s:
	$(MAKE) -f CMakeFiles/carbon.dir/build.make CMakeFiles/carbon.dir/src/carbon/carbon.c.s
.PHONY : src/carbon/carbon.c.s

src/carbon/strdic/carbon-strdic-sync.o: src/carbon/strdic/carbon-strdic-sync.c.o

.PHONY : src/carbon/strdic/carbon-strdic-sync.o

# target to build an object file
src/carbon/strdic/carbon-strdic-sync.c.o:
	$(MAKE) -f CMakeFiles/carbon.dir/build.make CMakeFiles/carbon.dir/src/carbon/strdic/carbon-strdic-sync.c.o
.PHONY : src/carbon/strdic/carbon-strdic-sync.c.o

src/carbon/strdic/carbon-strdic-sync.i: src/carbon/strdic/carbon-strdic-sync.c.i

.PHONY : src/carbon/strdic/carbon-strdic-sync.i

# target to preprocess a source file
src/carbon/strdic/carbon-strdic-sync.c.i:
	$(MAKE) -f CMakeFiles/carbon.dir/build.make CMakeFiles/carbon.dir/src/carbon/strdic/carbon-strdic-sync.c.i
.PHONY : src/carbon/strdic/carbon-strdic-sync.c.i

src/carbon/strdic/carbon-strdic-sync.s: src/carbon/strdic/carbon-strdic-sync.c.s

.PHONY : src/carbon/strdic/carbon-strdic-sync.s

# target to generate assembly for a file
src/carbon/strdic/carbon-strdic-sync.c.s:
	$(MAKE) -f CMakeFiles/carbon.dir/build.make CMakeFiles/carbon.dir/src/carbon/strdic/carbon-strdic-sync.c.s
.PHONY : src/carbon/strdic/carbon-strdic-sync.c.s

src/carbon/strdic/carbon-strdic_async.o: src/carbon/strdic/carbon-strdic_async.c.o

.PHONY : src/carbon/strdic/carbon-strdic_async.o

# target to build an object file
src/carbon/strdic/carbon-strdic_async.c.o:
	$(MAKE) -f CMakeFiles/carbon.dir/build.make CMakeFiles/carbon.dir/src/carbon/strdic/carbon-strdic_async.c.o
.PHONY : src/carbon/strdic/carbon-strdic_async.c.o

src/carbon/strdic/carbon-strdic_async.i: src/carbon/strdic/carbon-strdic_async.c.i

.PHONY : src/carbon/strdic/carbon-strdic_async.i

# target to preprocess a source file
src/carbon/strdic/carbon-strdic_async.c.i:
	$(MAKE) -f CMakeFiles/carbon.dir/build.make CMakeFiles/carbon.dir/src/carbon/strdic/carbon-strdic_async.c.i
.PHONY : src/carbon/strdic/carbon-strdic_async.c.i

src/carbon/strdic/carbon-strdic_async.s: src/carbon/strdic/carbon-strdic_async.c.s

.PHONY : src/carbon/strdic/carbon-strdic_async.s

# target to generate assembly for a file
src/carbon/strdic/carbon-strdic_async.c.s:
	$(MAKE) -f CMakeFiles/carbon.dir/build.make CMakeFiles/carbon.dir/src/carbon/strdic/carbon-strdic_async.c.s
.PHONY : src/carbon/strdic/carbon-strdic_async.c.s

src/carbon/strhash/carbon-strhash-mem.o: src/carbon/strhash/carbon-strhash-mem.c.o

.PHONY : src/carbon/strhash/carbon-strhash-mem.o

# target to build an object file
src/carbon/strhash/carbon-strhash-mem.c.o:
	$(MAKE) -f CMakeFiles/carbon.dir/build.make CMakeFiles/carbon.dir/src/carbon/strhash/carbon-strhash-mem.c.o
.PHONY : src/carbon/strhash/carbon-strhash-mem.c.o

src/carbon/strhash/carbon-strhash-mem.i: src/carbon/strhash/carbon-strhash-mem.c.i

.PHONY : src/carbon/strhash/carbon-strhash-mem.i

# target to preprocess a source file
src/carbon/strhash/carbon-strhash-mem.c.i:
	$(MAKE) -f CMakeFiles/carbon.dir/build.make CMakeFiles/carbon.dir/src/carbon/strhash/carbon-strhash-mem.c.i
.PHONY : src/carbon/strhash/carbon-strhash-mem.c.i

src/carbon/strhash/carbon-strhash-mem.s: src/carbon/strhash/carbon-strhash-mem.c.s

.PHONY : src/carbon/strhash/carbon-strhash-mem.s

# target to generate assembly for a file
src/carbon/strhash/carbon-strhash-mem.c.s:
	$(MAKE) -f CMakeFiles/carbon.dir/build.make CMakeFiles/carbon.dir/src/carbon/strhash/carbon-strhash-mem.c.s
.PHONY : src/carbon/strhash/carbon-strhash-mem.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... install/strip"
	@echo "... edit_cache"
	@echo "... carbon"
	@echo "... rebuild_cache"
	@echo "... list_install_components"
	@echo "... install/local"
	@echo "... install"
	@echo "... carbon-tool"
	@echo "... examples-error"
	@echo "... src/carbon/alloc/carbon-alloc-tracer.o"
	@echo "... src/carbon/alloc/carbon-alloc-tracer.i"
	@echo "... src/carbon/alloc/carbon-alloc-tracer.s"
	@echo "... src/carbon/carbon-alloc.o"
	@echo "... src/carbon/carbon-alloc.i"
	@echo "... src/carbon/carbon-alloc.s"
	@echo "... src/carbon/carbon-archive.o"
	@echo "... src/carbon/carbon-archive.i"
	@echo "... src/carbon/carbon-archive.s"
	@echo "... src/carbon/carbon-bitmap.o"
	@echo "... src/carbon/carbon-bitmap.i"
	@echo "... src/carbon/carbon-bitmap.s"
	@echo "... src/carbon/carbon-bloom.o"
	@echo "... src/carbon/carbon-bloom.i"
	@echo "... src/carbon/carbon-bloom.s"
	@echo "... src/carbon/carbon-columndoc.o"
	@echo "... src/carbon/carbon-columndoc.i"
	@echo "... src/carbon/carbon-columndoc.s"
	@echo "... src/carbon/carbon-convert.o"
	@echo "... src/carbon/carbon-convert.i"
	@echo "... src/carbon/carbon-convert.s"
	@echo "... src/carbon/carbon-doc.o"
	@echo "... src/carbon/carbon-doc.i"
	@echo "... src/carbon/carbon-doc.s"
	@echo "... src/carbon/carbon-error.o"
	@echo "... src/carbon/carbon-error.i"
	@echo "... src/carbon/carbon-error.s"
	@echo "... src/carbon/carbon-huffman.o"
	@echo "... src/carbon/carbon-huffman.i"
	@echo "... src/carbon/carbon-huffman.s"
	@echo "... src/carbon/carbon-json.o"
	@echo "... src/carbon/carbon-json.i"
	@echo "... src/carbon/carbon-json.s"
	@echo "... src/carbon/carbon-memblock.o"
	@echo "... src/carbon/carbon-memblock.i"
	@echo "... src/carbon/carbon-memblock.s"
	@echo "... src/carbon/carbon-memfile.o"
	@echo "... src/carbon/carbon-memfile.i"
	@echo "... src/carbon/carbon-memfile.s"
	@echo "... src/carbon/carbon-slicelist.o"
	@echo "... src/carbon/carbon-slicelist.i"
	@echo "... src/carbon/carbon-slicelist.s"
	@echo "... src/carbon/carbon-spinlock.o"
	@echo "... src/carbon/carbon-spinlock.i"
	@echo "... src/carbon/carbon-spinlock.s"
	@echo "... src/carbon/carbon-time.o"
	@echo "... src/carbon/carbon-time.i"
	@echo "... src/carbon/carbon-time.s"
	@echo "... src/carbon/carbon-vector.o"
	@echo "... src/carbon/carbon-vector.i"
	@echo "... src/carbon/carbon-vector.s"
	@echo "... src/carbon/carbon.o"
	@echo "... src/carbon/carbon.i"
	@echo "... src/carbon/carbon.s"
	@echo "... src/carbon/strdic/carbon-strdic-sync.o"
	@echo "... src/carbon/strdic/carbon-strdic-sync.i"
	@echo "... src/carbon/strdic/carbon-strdic-sync.s"
	@echo "... src/carbon/strdic/carbon-strdic_async.o"
	@echo "... src/carbon/strdic/carbon-strdic_async.i"
	@echo "... src/carbon/strdic/carbon-strdic_async.s"
	@echo "... src/carbon/strhash/carbon-strhash-mem.o"
	@echo "... src/carbon/strhash/carbon-strhash-mem.i"
	@echo "... src/carbon/strhash/carbon-strhash-mem.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

